<a href="https://colab.research.google.com/github/prad69/MLAssignments/blob/main/Linear_Regression_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Write a Python function that takes a matrix A and an integer k as input and returns the top k principal components of A using PCA.


Write a Python function that takes a matrix A as input and returns its singular value decomposition (SVD).


Write a Python code to derive simple linear regressions best-fit line in python

In [3]:
#Write a Python function that takes a matrix A and an integer k as input and returns the top k principal components of A using PCA.

import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
%matplotlib inline

def topKPrinciplaComponents(X ,k) :
  pca = PCA(n_components = None)
  x_PCA = pca.fit(X)
  return x_PCA


def pca(C,K) :
  eigen_vals , eigen_vecs = eigen_decomp(np.cov(C.T))
  idx = eigen_vals.argsort()[::-1]
  eigen_vals = eigen_vals[idx]
  eigen_vecs = eigen_vecs[:,idx]
  principal_components = eigen_vecs[:,:k]
  transformed = C.do(principal_components)
  return transformed

c= np.array([[1,2,4],[2,3,5],[4,6,7]])
print (c)
v = topKPrinciplaComponents(c,2)
v.explained_variance_ratio_

[[1 2 4]
 [2 3 5]
 [4 6 7]]


array([9.97938136e-01, 2.06186445e-03, 9.73961368e-33])

In [5]:
#Write a Python function that takes a matrix A as input and returns its singular value decomposition (SVD).


def svd(A):
  u, s, v = np.linalg.svd(A)
  return u,s,v

c=np.array([[1,2,4],[2,3,5],[4,6,7]])

svd(c)

(array([[-0.35572904, -0.71073018, -0.60689328],
        [-0.48813478, -0.41246406,  0.76915397],
        [-0.79698261,  0.56985613, -0.20020668]]),
 array([12.56981961,  1.40382724,  0.1700116 ]),
 array([[-0.35958583, -0.55352887, -0.75120158],
        [ 0.5298132 ,  0.54157961, -0.65267871],
        [ 0.76811197, -0.63269053,  0.09852255]]))

In [6]:
#Write a Python code to derive simple linear regressions best-fit line in python

import numpy as np

def simple_linear_regression(x, y):
    n = len(x)
    x_mean = np.mean(x)
    y_mean = np.mean(y)

    # Calculate the slope (beta_1) and intercept (beta_0)
    beta_1 = sum((x_i - x_mean)*(y_i - y_mean) for x_i, y_i in zip(x,y))/sum((x_i - x_mean)**2 for x_i in x)
    beta_0 = y_mean - beta_1*x_mean

    return beta_0, beta_1

# Example usage
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])
beta_0, beta_1 = simple_linear_regression(x, y)
print("Intercept (beta_0):", beta_0)
print("Slope (beta_1):", beta_1)

Intercept (beta_0): 2.2
Slope (beta_1): 0.6
